"""Add cascade delete to products and cart items

Revision ID: b1bc50f53cd0
Revises: 7a11c3fcdf61
Create Date: 2026-05-06 07:40:22.618562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1bc50f53cd0'
down_revision = '7a11c3fcdf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cart_items_product_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_items_product_id_fkey'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
