"""added is_best_seller and category

Revision ID: d6fff05ef3ce
Revises: 74e906cb1cf3
Create Date: 2026-04-01 01:27:46.941475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fff05ef3ce'
down_revision = '74e906cb1cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_best_seller', sa.Boolean(), nullable=True))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('is_best_seller')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
