"""add type to notifications

Revision ID: e01ba92d9b3d
Revises: 4ec4a55cad61
Create Date: 2026-05-09 12:38:36.332778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01ba92d9b3d'
down_revision = '4ec4a55cad61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('notif_type')

    # ### end Alembic commands ###
